---
title: "Starfsumhverfi stjórnenda í menningargeiranum á Íslandi"
subtitle: "Áskoranir, tækifæri og áherslur"
date: "`r Sys.Date()`"
format: pdf
author: "Kári Joensen"
---


```{r, echo=FALSE}
suppressMessages(
library(tidyverse))
suppressWarnings(
library(wesanderson)
)
library(knitr)
suppressMessages(
suppressWarnings(library(kableExtra))
)
```

```{r, echo=FALSE}
dat<- read.csv2(file = "results-survey145886.csv", sep = ",")
q_item<-read.csv2(file = "q_item.csv", fileEncoding = "ISO-8859-1")
q_text<-read.csv2(file = "q_text.csv", fileEncoding = "ISO-8859-1")

# Dálkaheiti fyrir fyrstu 10 spurningarnar
colnames(dat)[]<-t(q_item[,6
                              ])

dat<-dat %>% filter(lastPage==4)

lvl_askorun<-c("Mjög lítil / engin áskorun","Frekar lítil áskorun","Hvorki mikil né lítil áskorun","Frekar mikil áskorun","Mjög mikil áskorun","Veit ekki / vil ekki svara","")
lvl_taekifaeri<-c("Mjög lítil / engin tækifæri","Frekar lítil tækifæri","Hvorki mikil né lítil tækifæri","Frekar mikil tækifæri","Mjög mikil tækifæri","Veit ekki / vil ekki svara","")
lvl_sammala<-c("Mjög ósammála","Frekar ósammála","Hvorki sammála né ósammála","Frekar sammála","Mjög sammála","Veit ekki / vil ekki svara","")
lvl_okostur<-c("Mjög lítill / enginn ókostur","Frekar lítill ókostur","Hvorki mikill né lítill ókostur","Frekar mikill ókostur","Mjög mikill ókostur","Veit ekki / vil ekki svara","")
lvl_kostur<-c("Mjög lítill / enginn kostur","Frekar lítill kostur","Hvorki mikill né lítill kostur","Frekar mikill kostur","Mjög mikill kostur","Veit ekki, vil ekki svara","")

fct_skipulagsheild <- c("Ég starfa sjálfstætt", "Einkafyrirtæki", "Opinber menningarstofnun",                "Samvinnufélag", "Sjálfseignarstofnun", "Tímabundið verkefni á vegum hins opinbera", "Annað","")
dat[,167]<-factor(dat[,167], levels = fct_skipulagsheild)

for (i in 23:32) {
dat[,i]<-factor(dat[,i], levels = lvl_taekifaeri)
}

```


# Inngangur

## I. hluti: Áskoranir, tækifæri og áherslur

### `r str_wrap(q_text[2,2],width=900)`
\newpage



```{r, echo=FALSE, eval=FALSE, results='asis'}

for(i in 23:32){
  plot_dat<-data.frame(q=dat[,i]) %>% count(q) %>% complete(q,fill = list(n=integer(1),freq=0)) %>% mutate(freq=n/sum(n))
  plot_dat$freq_percent_lbl<-scales::percent(plot_dat$freq)
  
  my_plot<-ggplot(
    data = plot_dat,
    aes(x=q, y=freq, fill=q)
  )+
    geom_bar(stat = "identity")+
    labs(title = str_wrap(q_item[i,4], width = 120) ,subtitle = "Tækifæri fyrir menningarstarfsemi")+
    theme_classic()+
    theme(legend.position = "none")+
    scale_x_discrete(labels=function(x) str_wrap(x,width = 15))+
    scale_fill_brewer(palette = "YlGn")+
    theme(axis.title.x=element_blank())+theme(axis.title.y=element_blank())+
    scale_y_continuous(labels = scales::percent)
  print(my_plot)
  print(kable(plot_dat[-3]) %>% column_spec(2:3, bold = TRUE) ) 
  cat("\n")
}
remove(plot_dat, my_plot)
  
```

```{r, echo=FALSE, results='asis'}
# Spurning 2.7
# Samlegðartækifæri eða sameining

for(i in 29:29){
  
  plotdat <- data.frame(q=dat[,c(i,167)])
  colnames(plotdat)<-c("x","y")
  # ggplot(plotdat, aes(x=x, fill=y))+geom_bar(position = "dodge")
  plotdat <- plotdat %>% 
    group_by(y) %>% 
    count(x) %>% 
    # complete(y, fill = list(n=integer(1), freq=0)) %>% 
    complete(x, fill = list(n=integer(1), freq=0)) %>% 
    mutate(freq=n/sum(n))  
  
  for(j in 1:7){
      my_plotdata<-plotdat %>% filter(y==fct_skipulagsheild[j])
      my_plot<-ggplot(my_plotdata, aes(x=x, y=freq, fill=x))+
      geom_col()+
      labs(title = str_wrap(q_item[i,4], width = 64) ,subtitle = fct_skipulagsheild[j])+
      theme_classic()+
      theme(legend.position = "none")+
      scale_x_discrete(labels=function(x) str_wrap(x,width = 10))+
      scale_fill_brewer(palette = "YlGn")+
      theme(axis.title.x=element_blank())+theme(axis.title.y=element_blank())+
      scale_y_continuous(labels = scales::percent)
      plot(my_plot)
      print(kable(my_plotdata[-1], caption =fct_skipulagsheild[j] ) %>% column_spec(2:3, bold = TRUE) ) 
      cat("\n")
      remove(my_plotdata,my_plot)
    }
  
  remove(plotdat)
}
```

```{r, echo=FALSE, results='asis'}

for(i in 29:29){
  
  plotdat <- data.frame(q=dat[,c(i,167)])
  colnames(plotdat)<-c("x","y")
  # ggplot(plotdat, aes(x=x, fill=y))+geom_bar(position = "dodge")
  plotdat <- plotdat %>% 
    group_by(y) %>% 
    count(x) %>% 
    # complete(y, fill = list(n=integer(1), freq=0)) %>% 
    complete(x, fill = list(n=integer(1), freq=0)) %>% 
    mutate(freq=n/sum(n))  
  
   remove(plotdat)
}

```


